---
title: "Gather Tweets"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE,
                      message = FALSE, warning = FALSE,
                      dpi = 180, fig.height = 8, fig.width = 5)
```

```{r libraries}
library(rtweet)
# https://www.rdocumentation.org/packages/rtweet/versions/0.7.0/topics/search_tweets
library(tidyverse)

token <- create_token(
  app = 'marketingguy_text_mining',
  consumer_key = 'ReFDEfRS2s2jNbVIsNtU8rhEA',
  consumer_secret = 'nWWIPUlFAPQxeK688pw45pu541BJVHmZLa1mU0haBZV2zIUqqo',
  access_token = '18102142-on6G71rQMJm7wr4MoiW83jko8s5nFB7iuZGoZxupZ',
  access_secret = '84Z3Ab3uP7nQSdMn52tJXC64JZZG8mxD9ViBG4jsjnFjY')

search_date <- Sys.Date()-1
```

```{r tweets}
bay_area <- search_tweets(
                        "@WaveConnects OR
                        @gowave_g OR
                        @ATT OR 
                        @Xfinity OR
                        @comcast OR
                        @comcastcares OR
                        @FrontierCorp OR
                        @sonicnet OR
                        @MyCCITweets
                        ",
                        n = 10000,
                        include_rts = FALSE, 
                        retryonratelimit = TRUE,
                        # SFO
                        geocode = "37.77,-122.43,25mi",  
                        lang = "en",
                        since=search_date
                        )

bay_area$created_at <- format(bay_area$created_at, format= "%Y-%m-%dT%H:%M:%S.000")
bay_area$region <- "Bay Area"
bay_area$market <- "Wave South"
bay_area$src <- "Twitter"
bay_area <- bay_area %>%
  mutate(brand =
           case_when(
             str_detect(text,"@WaveConnects") ~ "Wave",
             str_detect(text,"@gowave_g") ~ "Wave",
             str_detect(text,"@ATT") ~ "ATT",
             str_detect(text,"AT&T") ~ "ATT",
             str_detect(text,"@FrontierCorp") ~ "Frontier",
             str_detect(text,"@MyCCITweets") ~ "Consolidated",
             str_detect(text,"@Xfinity") ~ "Xfinity",
             str_detect(text,"@comcastcares") ~ "Xfinity",
             str_detect(text,"@Comcast") ~ "Xfinity",
             str_detect(text,"@comcast") ~ "Xfinity",
             str_detect(text,"@sonicnet") ~ "SonicNet",
             str_detect(text,"Comcast") ~ "Xfinity",
             str_detect(text,"comcast") ~ "Xfinity",
             str_detect(text,"xfinity") ~ "Xfinity",
             str_detect(text,"Xfinity") ~ "Xfinity",
             str_detect(text,"XFinity") ~ "Xfinity",
             TRUE ~ "Other"
                     )) %>%
  filter(brand != "Other")
bay_area <- bay_area %>% select(created_at,text,src,brand,region,location,market)
# write_as_csv(bay_area, "C:\\Users\\chbailey\\Documents\\sent_app\\bay_area.csv", prepend_ids = TRUE, na = "", fileEncoding = "UTF-8")
```

```{r tweets}
sac <- search_tweets(
                        "@WaveConnects OR
                        @gowave_g OR 
                        @ATT OR 
                        @Xfinity OR
                        @comcast OR
                        @comcastcares OR
                        @MyCCITweets OR
                        @FrontierCorp OR
                        @sonicnet
                        ",
                        n = 10000,
                        include_rts = FALSE, 
                        retryonratelimit = TRUE,
                        # Sacramento/Roseville/Rocklin/Lincoln/Auburn/North Auburn/Granite Bay/Woodland
                        geocode = "38.57,-121.47,50mi",  
                        lang = "en",
                        since=search_date
                        )

sac$created_at <- format(sac$created_at, format= "%Y-%m-%dT%H:%M:%S.000")
sac$region <- "Sacramento"
sac$market <- "Wave South"
sac$src <- "Twitter"
sac <- sac %>%
  mutate(brand =
           case_when(
             str_detect(text,"@WaveConnects") ~ "Wave",
             str_detect(text,"@gowave_g") ~ "Wave",
             str_detect(text,"@ATT") ~ "ATT",
             str_detect(text,"AT&T") ~ "ATT",
             str_detect(text,"@FrontierCorp") ~ "Frontier",
             str_detect(text,"@MyCCITweets") ~ "Consolidated",
             str_detect(text,"@Xfinity") ~ "Xfinity",
             str_detect(text,"@xfinity") ~ "Xfinity",
             str_detect(text,"@comcastcares") ~ "Xfinity",
             str_detect(text,"@Comcast") ~ "Xfinity",
             str_detect(text,"@comcast") ~ "Xfinity",
             str_detect(text,"@sonicnet") ~ "SonicNet",
             str_detect(text,"Comcast") ~ "Xfinity",
             str_detect(text,"comcast") ~ "Xfinity",
             str_detect(text,"xfinity") ~ "Xfinity",
             str_detect(text,"Xfinity") ~ "Xfinity",
             str_detect(text,"XFinity") ~ "Xfinity",
             TRUE ~ "Other"
                     )) %>%
  filter(brand != "Other")
sac <- sac %>% select(created_at,text,src,brand,region,location,market)
# write_as_csv(sac, "C:\\Users\\chbailey\\Documents\\sent_app\\sac.csv", prepend_ids = TRUE, na = "", fileEncoding = "UTF-8")
```

<!-- ```{r tweets} -->
<!-- garb <- search_tweets( -->
<!--                         "@WaveConnects OR -->
<!--                         @gowave_g", -->
<!--                         n = 10000, -->
<!--                         include_rts = FALSE,  -->
<!--                         retryonratelimit = TRUE, -->
<!--                         # Garberville/Redway/Benbow -->
<!--                         geocode = "40.10,-123.79,100mi",   -->
<!--                         lang = "en", -->
<!--                         since=search_date -->
<!--                         ) -->

<!-- garb$created_at <- format(garb$created_at, format= "%Y-%m-%dT%H:%M:%S.000") -->
<!-- garb$region <- "Garberville" -->
<!-- garb$market <- "Wave South" -->
<!-- garb$src <- "Twitter" -->
<!-- garb <- garb %>% -->
<!--   mutate(brand = -->
<!--            case_when( -->
<!--              str_detect(text,"@WaveConnects") ~ "Wave", -->
<!--              str_detect(text,"@gowave_g") ~ "Wave", -->
<!--              TRUE ~ "Other" -->
<!--                      )) %>% -->
<!--   filter(brand != "Other") -->
<!-- garb <- garb %>% select(created_at,text,src,brand,region,location,market) -->
<!-- write_as_csv(garb, "C:\\Users\\chbailey\\Documents\\sent_app\\garb.csv", prepend_ids = TRUE, na = "", fileEncoding = "UTF-8") -->
<!-- ``` -->

```{r tweets, include=FALSE}
portland <- search_tweets(
                        "@WaveConnects OR 
                        @gowave_g OR
                        @Xfinity OR
                        @comcast OR
                        @comcastcares OR
                        @GetSpectrum OR
                        @CenturyLink OR
                        @CenturyLinkHome OR
                        @DirectLinkCoop",
                        n = 10000,
                        include_rts = FALSE, 
                        retryonratelimit = TRUE,
                        geocode = "45.52,-122.67,75mi",  
                        lang = "en",
                        since=search_date
                        )

portland$created_at <- format(portland$created_at, format= "%Y-%m-%dT%H:%M:%S.000")
portland$region <- "Portland"
portland$market <- "Wave South"
portland$src <- "Twitter"
portland <- portland %>%
  mutate(brand =
           case_when(
             str_detect(text,"@WaveConnects") ~ "Wave",
             str_detect(text,"@gowave_g") ~ "Wave",
             str_detect(text,"@GetSpectrum") ~ "Spectrum",
             str_detect(text,"@Ask_Spectrum") ~ "Spectrum",
             str_detect(text,"@CenturyLink") ~ "CenturyLink",
             str_detect(text,"@CenturyLinkHome") ~ "CenturyLink",
             str_detect(text,"@centurylink") ~ "CenturyLink",
             str_detect(text,"@Xfinity") ~ "Xfinity",
             str_detect(text,"@comcastcares") ~ "Xfinity",
             str_detect(text,"@Comcast") ~ "Xfinity",
             str_detect(text,"@comcast") ~ "Xfinity",
             str_detect(text,"@DirectLinkCoop") ~ "DirectLink",
             str_detect(text,"@CityofSandyOR") ~ "CityofSandyOR",
             str_detect(text,"Comcast") ~ "Xfinity",
             str_detect(text,"comcast") ~ "Xfinity",
             str_detect(text,"xfinity") ~ "Xfinity",
             str_detect(text,"Xfinity") ~ "Xfinity",
             str_detect(text,"XFinity") ~ "Xfinity",
             TRUE ~ "Other"
                     )) %>%
  filter(brand != "Other")
portland <- portland %>% select(created_at,text,src,brand,region,location,market)
# write_as_csv(portland, "C:\\Users\\chbailey\\Documents\\sent_app\\portland.csv", prepend_ids = TRUE, na = "", fileEncoding = "UTF-8")
```

```{r tweets}
seattle <- search_tweets(
                        "@WaveConnects OR 
                        @gowave_g OR
                        @Xfinity OR
                        @comcast OR
                        @comcastcares OR
                        @ZiplyFiber OR
                        @CenturyLink OR
                        @CenturyLinkHome
                        ",
                        n = 10000,
                        include_rts = FALSE, 
                        retryonratelimit = TRUE,
                        # Seattle
                        geocode = "47.60,-122.33,140mi",  
                        lang = "en",
                        since=search_date
                        )

seattle$created_at <- format(seattle$created_at, format= "%Y-%m-%dT%H:%M:%S.000")
seattle$region <- "Seattle"
seattle$market <- "Wave North"
seattle$src <- "Twitter"
seattle <- seattle %>%
  mutate(brand =
           case_when(
             str_detect(text,"@WaveConnects") ~ "Wave",
             str_detect(text,"@gowave_g") ~ "Wave",
             str_detect(text,"@Xfinity") ~ "Xfinity",
             str_detect(text,"@comcastcares") ~ "Xfinity",
             str_detect(text,"@Comcast") ~ "Xfinity",
             str_detect(text,"@comcast") ~ "Xfinity",
             str_detect(text,"Comcast") ~ "Xfinity",
             str_detect(text,"comcast") ~ "Xfinity",
             str_detect(text,"xfinity") ~ "Xfinity",
             str_detect(text,"Xfinity") ~ "Xfinity",
             str_detect(text,"XFinity") ~ "Xfinity",
             str_detect(text,"@CenturyLinkHome") ~ "CenturyLink",
             str_detect(text,"@centurylink") ~ "CenturyLink",
             str_detect(text,"CenturyLink") ~ "CenturyLink",
             str_detect(text,"centurylink") ~ "CenturyLink",
             str_detect(text,"@ZiplyFiber") ~ "Ziply",
             str_detect(text,"@ziplyfiber") ~ "Ziply",
             str_detect(text,"Ziply") ~ "Ziply",
             str_detect(text,"ziply") ~ "Ziply",
             TRUE ~ "Other"
                     )) %>%
  filter(brand != "Other")
seattle <- seattle %>% select(created_at,text,src,brand,region,location,market)
# write_as_csv(seattle, "C:\\Users\\chbailey\\Documents\\sent_app\\seattle.csv", prepend_ids = TRUE, na = "", fileEncoding = "UTF-8")
```

```{r tweets}
all_markets <- do.call("rbind", list(bay_area, sac, portland, seattle))
write_as_csv(all_markets, "C:\\Users\\chbailey\\Documents\\sent_app\\all_markets.csv", prepend_ids = TRUE, na = "", fileEncoding = "UTF-8")
```